version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm (for LSP servers, etc.)
  - package-ecosystem: "npm"
    directory: "/" # Assuming a package.json might be added at the root
    schedule:
      interval: "weekly"
